### ISSUE TITLE
🐛 [BUG] Can't see the Sign in with Discord button on mobile view

### ISSUE THREAD

**Issue by MidouWebDev** [Heptagram-Project/website#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While checking the website on mobile, i saw that in the hamburger menu we can't see the button so we can't use it at all.

### Expected Behavior

I expected to see the button so that i can use it as a mobile visitor.

### Steps To Reproduce

1. On your phone, go to the Homepage
2. Click on the hamburger icon to open the menu
3. See that the button isn't there

**Comment by nitin094-hub** [comment]
Can I work on this issue?

**Comment by MidouWebDev** [comment]
@nitin094-hub sure thanks a lot !
